#Springboot profiles & devtools related property configuration
spring:
  application:
    name: eureka-discovery-server
  profiles:
    active: dev
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

server:
  port: 8761

#Springboot actuator related property configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#Eureka server related property configuration
eureka:
  instance:
    hostname: localhost
  client:
    prefer-ip-address: true
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://discovery:8761/eureka
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
    renewal-percent-threshold: 0.85
    response-cache-update-interval-ms: 30000
    maximum-time-to-wait-for-ack-ms: 5000
    enable-http2: true



