server:
  port: 8761  # The port on which the Eureka server will run

eureka:
  instance:
    hostname: localhost  # The hostname of the Eureka server instance

  client:
    registerWithEureka: false  # Don't register the server with itself
    fetchRegistry: false  # Don't fetch the registry from itself
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # URL for clients to register with Eureka

spring:
  application:
    name: eureka-server  # Name of the application

logging:
  level:
    com.netflix.eureka: INFO  # Logging level for Eureka
    org.springframework.cloud.netflix.eureka: INFO  # Logging level for Spring Cloud Netflix Eureka
    root: INFO  # Default logging level
